#THIS IS AN INTERACTIVE CODING EXERCISE FROM ANGELA YU WORKING WITH VARIABLES
#THIS GOAL IS TO CONVERT USERS INPUT TO NUMBER BY PRINTING THE NUMBER OF CHAR
#SEARCH FOR IT AND FOUND OUT YOU USE THE LENSE FUNCTION FOR THIS>

print(len(input("what is your name")))
